FROM node:22.14.0-alpine
WORKDIR /dedsec.cl
COPY ./package.json /dedsec.cl
COPY ./tsconfig.json /dedsec.cl
COPY ./tsconfig.app.json /dedsec.cl
COPY ./angular.json /dedsec.cl
COPY ./src/ /dedsec.cl/src/
RUN npm install
CMD ["npm", "run", "watch"]
